### Get all songs
GET http://localhost:3000/songs?page=1&limit=2

### Get a song by ID
GET http://localhost:3000/songs/7

### Update a song by ID
PUT http://localhost:3000/songs/1
Content-Type: application/json

{
  "title": "lasting lover 2 updated title"
}

### Delete a song by ID
DELETE http://localhost:3000/songs/1

### Create a new song
POST http://localhost:3000/songs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5kb2UyQGdtYWlsLmNvbSIsInVzZXJJZCI6NiwiYXJ0aXN0SWQiOjMsImlhdCI6MTcxNTM1MzY4MCwiZXhwIjoxNzE1NDQwMDgwfQ.dErhy34JS8QmsSsz0Otz2USU9RUYmPe3zTEL7v-4sig

{
  "title": "You for Me 2",
  "artists": [1, 2],
  "releasedDate": "2023-10-29",
  "duration": "02:34",
  "lyrics": "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
}

### Signup User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "firstName": "Sam",
  "lastName": "Alt",
  "email": "samalt@gmail.com",
  "password": "12345678"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "johndoe2@gmail.com",
  "password": "12345678"
}

### Profile
GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5kb2UyQGdtYWlsLmNvbSIsInVzZXJJZCI6NiwiYXJ0aXN0SWQiOjMsImlhdCI6MTcxNTM1MzY4MCwiZXhwIjoxNzE1NDQwMDgwfQ.dErhy34JS8QmsSsz0Otz2USU9RUYmPe3zTEL7v-4sig

### Enable 2FA
POST http://localhost:3000/auth/enable-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5kb2UyQGdtYWlsLmNvbSIsInVzZXJJZCI6NiwiYXJ0aXN0SWQiOjMsImlhdCI6MTcxNTQyNjU1NiwiZXhwIjoxNzE1NTEyOTU2fQ.Rs09xn5Lh5GkMRTMcE-kolmMrr5OUtjXNrVSrnqOrIE

### Disable 2FA
POST http://localhost:3000/auth/disable-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5kb2UyQGdtYWlsLmNvbSIsInVzZXJJZCI6NiwiYXJ0aXN0SWQiOjMsImlhdCI6MTcxNTQyNjU1NiwiZXhwIjoxNzE1NTEyOTU2fQ.Rs09xn5Lh5GkMRTMcE-kolmMrr5OUtjXNrVSrnqOrIE

### Verify 2FA
POST http://localhost:3000/auth/validate-2fa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5kb2UyQGdtYWlsLmNvbSIsInVzZXJJZCI6NiwiYXJ0aXN0SWQiOjMsImlhdCI6MTcxNTQyNjU1NiwiZXhwIjoxNzE1NTEyOTU2fQ.Rs09xn5Lh5GkMRTMcE-kolmMrr5OUtjXNrVSrnqOrIE

{
  "token": "713543"
}


### Auth Profile
GET http://localhost:3000/auth/profile
Authorization: Bearer e0b87bd2-c4cd-4876-955f-6f7a8dd2de97

### TEST ENV VARIABLES
GET http://localhost:3000/auth/test