### Get all songs
GET http://localhost:3000/songs?page=1&limit=2

### Get a song by ID
GET http://localhost:3000/songs/7

### Update a song by ID
PUT http://localhost:3000/songs/1
Content-Type: application/json

{
  "title": "lasting lover 2 updated title"
}

### Delete a song by ID
DELETE http://localhost:3000/songs/1

### Create a new song
POST http://localhost:3000/songs
Content-Type: application/json

{
  "title": "You for Me",
  "artists": [1, 2],
  "releasedDate": "2023-10-29",
  "duration": "02:34",
  "lyrics": "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
}